### ISSUE TITLE
Franz autoupdate overwrites Ferdi

### ISSUE THREAD

**Issue by justus-saul** [kytwb/ferdi#16]
When there is a new Franz version, but not a new Ferdi version yet. You get to see the update banner at the bottom of the screen. When you click it Franz is automatically installed and Ferdi is gone.

**Comment by kytwb** [comment]
Thought this was fixed already but we had some mix up happen with a GitHub app that forced-push on the repository. Re-applied via https://github.com/kytwb/ferdi/commit/e501af3f0e0df1c91240622e4d312ae95025406c. Will update the latest release asap.

**Comment by kytwb** [comment]
Waiting for the builds to finish:
<img width="692" alt="Screen Shot 2019-08-18 at 7 40 35 AM" src="https://user-images.githubusercontent.com/412895/63218746-88212800-c18b-11e9-8e8d-9f6311aaeb79.png">

**Comment by kytwb** [comment]
Updated the latest release assets with the latest builds artifacts: https://github.com/kytwb/ferdi/releases/tag/Ferdi-5.2.1-beta.1
