### ISSUE TITLE
Brew cask support

### ISSUE THREAD

**Issue by BinaryShrub** [kytwb/ferdi#18]
`brew cask install ferdi`

**Comment by vantezzen** [comment]
Related:
<https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md> and <https://github.com/Homebrew/homebrew-cask/blob/master/Casks/franz.rb>

**Comment by kytwb** [comment]
Had to name the cask `franz-ferdi` as we are in the fork category:

> Fork: An alternate version of an existing project, with a based-on but modified source and binary.

> Forks should have the vendor’s name as a prefix on the Cask’s file name and token. For unrelated Apps that share a name, the most popular one (usually the one already present) stays unprefixed. Since this can be subjective, if you disagree with a decision, open an issue and make your case to the maintainers.

See https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#forks-and-apps-with-conflicting-names.

**Comment by kytwb** [comment]
Pull request merged 🎉

```
kytwbs-MacBook-Pro:Desktop kytwb$ brew cask install ferdi
Error: Cask 'ferdi' is unavailable: No Cask with this name exists.
``` 

Will close once available and after adding to the README.

**Comment by kytwb** [comment]
```
kytwbs-MacBook-Pro:~ kytwb$ brew cask install ferdi
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
atk                                            osslsigncode                                   svtplay-dl                                     yelp-tools

==> Satisfying dependencies
==> Downloading https://github.com/kytwb/ferdi/releases/download/v5.3.0/Ferdi-5.3.0.dmg
Already downloaded: /Users/kytwb/Library/Caches/Homebrew/downloads/253ffc4cce455cd1806e12dc1fafdb7f1f6c8a9a905b595112c60568e4e38c6a--Ferdi-5.3.0.dmg
==> Verifying SHA-256 checksum for Cask 'ferdi'.
==> Installing Cask ferdi
==> Moving App 'Ferdi.app' to '/Applications/Ferdi.app'.
🍺  ferdi was successfully installed!
```
