### ISSUE TITLE
Whatsapp Web not working, needs chrome 49+

### ISSUE THREAD

**Issue by ZeroCool940711** [kytwb/ferdi#21]
**Describe the bug**
After I updated to ferdi 5.3.0 whatsapp web service is no longer working, when you open it on ferdi it says that Chrome 49+ is needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5977640/64439809-ad64d000-d07f-11e9-9c14-1d4517be552a.png)

**Comment by AGCaesar** [comment]
Duplicate ob Bug #19  ;) Solution is mentioned there :)

**Comment by ZeroCool940711** [comment]
Oh, sorry for creating a duplicate, I guess I should had search first for any other open issue regarding this. :/
