### ISSUE TITLE
Merging Franz 5.3 into Ferdi

### ISSUE THREAD

**Issue by vantezzen** [kytwb/ferdi#23]
[Franz 5.3.0](https://github.com/meetfranz/franz/releases) was just released, adding Franz Todos and bringing some pricing updates with it.

Today I worked on merging Franz 5.3.0 into the Ferdi codebase (resulting in Ferdi 5.3.1), but the merged version may need some testing from volunteers.

@kytwb could you publish the latest builds from Travis and AppVeyor from the franz-5.3.0 branch as a pre-release build?

Things that need testing are:
- Does everything work as it should (all recipes etc.)?
- Are there any premium restrictions left?
- Does the new “Franz Todo“ feature work? Does it work with other todo services as intended?
- Are there any “Franz”’s left in the translations?/Is the Ferdi brand present everywhere?

Known issues:
- Franz Todo sometimes doesn’t work (not creating new tasks, reloading fixed this). This seems to be a problem with Franz Todo, not Ferdi

**Comment by kytwb** [comment]
What about https://github.com/kytwb/ferdi/pull/24? Did you pull the changes from Franz manually, then resolved the conflicts on the franz-5.3.0 branch? Are ok to still use the Pull bot as discussed in https://github.com/kytwb/ferdi/issues/9? Also, regarding the versioning, do you think we should keep the versions in sync with Franz?

**Comment by vantezzen** [comment]
There were quite some merge conflicts in #24 so I merged and resolved the changed into the franz-5.3.0 branch first. This way we can test if everything works before merging franz-5.3.0 into master.

The usage of Pull bot as discussed in #9 should still be ok with smaller changes, but as this is a whole new Franz version being merged (5.2.0 -> 5.3.0), this PR needed to be resolved manually.

I think it would be best to keep the versioning between Franz and Ferdi in sync.

**Comment by kytwb** [comment]
Roger that. So should I first update Ferdi v5.3.0 release to includes todos? I'm afraid it would be confusing for people downloading Ferdi 5.3.0 expecting features parity with Franz 5.3.0 otherwise.

**Comment by vantezzen** [comment]
I would keep the current Ferdi 5.3.0 pre-release as is and release the franz-5.3.0 branch as Ferdi 5.3.1.

Mainly because the franz-5.3.0 branch is already up to date to Franz 5.3.1. Releasing that as 5.3.0 could also cause confusions and people could think that Ferdi is not up to date with Franz releases.

**Comment by vantezzen** [comment]
I havn't found any more bugs, we can publish 5.3.1 if you want to.

Can you add the builds to the GitHub release and update homebrew?

**Comment by kytwb** [comment]
@vantezzen been a bit busy lately, will take care of the releases today.

**Comment by kytwb** [comment]
Released [v5.3.1](https://github.com/kytwb/ferdi/releases/tag/v5.3.1) and [v5.3.2](https://github.com/kytwb/ferdi/releases/tag/v5.3.2)

**Comment by kytwb** [comment]
Updating the cask as well.
