### ISSUE TITLE
Missing Ferdi branding

### ISSUE THREAD

**Issue by justus-saul** [kytwb/ferdi#25]
I am using Ferdi-5.3.0 on ubuntu, installed it via the.deb file and German as set language.
I discovered that there are at least the occurrences of Franz left.

1. The title of the application still says Franz 
2. Menu: "Fenster" (window) -> "Über Franz" (about Franz)
3. The "Über Franz" (about Franz) window still shows Franz information

**Comment by bittner** [comment]
These are screenshots of the issues mentioned above:

![Franz-Ferdi-window-title](https://user-images.githubusercontent.com/665072/64515539-0be2b600-d2ed-11e9-9bf4-4924559a25c1.png)

![Franz-Ferdi-About-menu](https://user-images.githubusercontent.com/665072/64515911-c5418b80-d2ed-11e9-9a04-8c1d57dd1291.png)

![Franz-Ferdinand-About-box](https://user-images.githubusercontent.com/665072/64465844-04fe4c80-d10f-11e9-8366-ad2f042ccb8a.png)

In https://github.com/kytwb/ferdi/issues/2#issuecomment-529047886 I suggested that we keep the link to Franz (to avoid irritation for users coming from Franz, and also as a sweet historical relation). See https://github.com/kytwb/ferdi/issues/2#issuecomment-508767896 for more details. 

Specifically, can we set
1. the About menu item to "Ferdi" (`Franz` -> `Ferdi`),
1. the About box _title_ to "Ferdi" (`Franz` -> `Ferdi`), and
1. the About box window title may get `Ferdi` for consistency also, but the _header_ of the About box text could be "Franz Ferdinand" (`Franz` -> `Franz Ferdinand`)

That would be nice!

**Comment by vantezzen** [comment]
Thank you for the feedback.
The branding issues should now be fixed as of Ferdi 5.3.1.

@bittner I have now changed the About menu **title** to "Franz Ferdinand". The about-menu header always shows the application name - so showing a different name could case confusions. The window title on the other hand seems to vary between applications ("About", "About application", application name etc.), allowing us to show "Franz Ferdinand" instead.

**Comment by kytwb** [comment]
LGTM 👍 Thanks for the reporting @justus-saul @bittner, and @vantezzen for the fixes. Will be available in the next/updated release. Closing for now.
