### ISSUE TITLE
Missing spacing between link and text in settings

### ISSUE THREAD

**Issue by justus-saul** [kytwb/ferdi#26]
Ferdi version 5.3.0 on Ubuntu 18.04.3 LTS 64-bit
![grafik](https://user-images.githubusercontent.com/5861826/64530896-79eba500-d30e-11e9-9aa6-85797ffbe9be.png)

**Comment by kytwb** [comment]
Related to https://github.com/kytwb/ferdi/blob/7d584c14d3eecd08644d3035730d9e07f195cb78/src/components/settings/settings/EditSettingsForm.js#L269

**Comment by vantezzen** [comment]
Thank you for your feedback.

This problem should already be resolved in Ferdi 5.3.1
![Screenshot](https://user-images.githubusercontent.com/10333196/64537942-08b2ee80-d31c-11e9-916f-6341fbe11d0c.png)

**Comment by kytwb** [comment]
Will be available in the next/updated release.  
🙏 Thank you for reporting.
