### ISSUE TITLE
Windows: Taskbar title is still "Franz"

### ISSUE THREAD

**Issue by VerstandInvictus** [kytwb/ferdi#28]
**Describe the bug**
In Windows 10, the taskbar title for Ferdi is still Franz, though the purple Ferdi logo is shown correctly.

**To Reproduce**
1. Launch Ferdi 5.3.0 on Windows
2. Observe taskbar

**Expected behavior**
Ferdi should be shown as the taskbar title

**Screenshots**
![image](https://user-images.githubusercontent.com/14807375/64740449-4180ce00-d4aa-11e9-9d9c-dab1572ea151.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 77

**Additional context**
Even the process name is ferdi.exe, so I'm not sure where the title is coming from.

**Comment by vantezzen** [comment]
Thank you for your feedback.

I just [fixed the bug](https://github.com/kytwb/ferdi/blob/828f4bce4ee1d7c53c132f0cce6032c121632015/src/index.html#L4), the fix should be released in 5.3.1

**Comment by kytwb** [comment]
Released in https://github.com/kytwb/ferdi/releases/tag/v5.3.1
