### ISSUE TITLE
Installing this fork

### ISSUE THREAD

**Issue by xthursdayx** [kytwb/ferdi#3]
This may be a stupid question, but can anyone tell me how to install this fork in MacOS? I just used the regular .dmg installer when I installed the original version. Thanks!

**Comment by kytwb** [comment]
I will make the installers available shortly.

**Comment by xthursdayx** [comment]
Great, thanks. I'll keep my eye out for them. 

My impression is that on MacOS if you follow the brew build instructions it will just install the original version of Franz. I'm not sure how to specify this fork (or if that is even possible). I know that you can compile this package using Xcode in MacOS, but I didn't really feel like installing that program (~8Gb) just to compile this one app.

**Comment by kytwb** [comment]
Don't need to install Xcode to build Franz. You need primarily need Node.js/npm (there might be other dependencies baseed on your system) and run the packaging command as per the README: `npm run build`. I'm going to run it locally and make the distributable(s) it produces available.

**Comment by kytwb** [comment]
Pre-release available here: https://github.com/kytwb/ferdi/releases/tag/Ferdi-5.0.0-beta.24

**Comment by xthursdayx** [comment]
Thanks @kytwb ! I actually ended up figuring out how to use npm to build it myself, but I'll switch over to your release once you get take it out of beta.

**Comment by ratsuns** [comment]
installed the Franz-5.0.0-beta.24.dmg and works great except the lower three icons do not load.

Screen Shot 2019-04-05 at 10 59 37 AM](https://user-images.githubusercontent.com/27666567/55647199-eed01700-5791-11e9-9c82-9b159fbb6b5a.png)

**Comment by kytwb** [comment]
Thanks for the feedback, I will double check!

**Comment by kytwb** [comment]
@ratsuns see https://github.com/meetfranz/franz/issues/1433

**Comment by bittner** [comment]
*Cross-posting here from https://github.com/kytwb/ferdi/issues/4#issuecomment-495994693:*

We should really try to make [all-platform automatic builds](https://github.com/meetfranz/franz/releases/) upon releases. Just like Franz and similar projects. Electron builds for almost every installation technology (snaps, flatpack, etc. excluded I believe).

**Comment by anmoljagetia** [comment]
I am getting the following error when I try to build on Mojave : 

```
ferdi master ✗ △ ➜ npm install

> franz@5.1.0 postinstall /private/tmp/ferdi
> npx lerna run prepare

lerna notice cli v3.14.1
lerna info versioning independent
lerna info Executing command in 3 packages: "npm run prepare"
lerna info run Ran npm script 'prepare' in '@meetfranz/theme' in 12.4s:

> @meetfranz/theme@1.0.13 prepare /private/tmp/ferdi/packages/theme
> tsc

lerna ERR! npm run prepare exited 2 in '@meetfranz/forms'
lerna ERR! npm run prepare stdout:

> @meetfranz/forms@1.0.15 prepare /private/tmp/ferdi/packages/forms
> tsc

src/button/index.tsx(238,11): error TS2322: Type 'string | undefined' is not assignable to type '"button" | "reset" | "submit" | undefined'.
  Type 'string' is not assignable to type '"button" | "reset" | "submit" | undefined'.

lerna ERR! npm run prepare stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @meetfranz/forms@1.0.15 prepare: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @meetfranz/forms@1.0.15 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anmol.j/.npm/_logs/2019-06-03T20_05_06_009Z-debug.log

lerna ERR! npm run prepare exited 2 in '@meetfranz/forms'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! franz@5.1.0 postinstall: `npx lerna run prepare`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the franz@5.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anmol.j/.npm/_logs/2019-06-03T20_05_06_095Z-debug.log
```

**Comment by kytwb** [comment]
@bittner https://travis-ci.org/kytwb/ferdi/jobs/552771419 via https://github.com/kytwb/ferdi/commit/e3c8423bd4db6a201dd791caca01600b55c5e1d8, building to http://ferdi-travis.s3.amazonaws.com.

**Comment by kytwb** [comment]
Everyone, please see https://github.com/kytwb/ferdi/releases/tag/Ferdi-5.2.0-beta.3 for the latest release.
