### ISSUE TITLE
Windows executable?

### ISSUE THREAD

**Issue by FairlyIncognito** [kytwb/ferdi#4]
Any chance for a Windows installation file?
I attempted building it myself but failed.
Cheers.

**Comment by raddacle** [comment]
Yes please!

**Comment by kytwb** [comment]
I will see what I can do shortly, thanks for your patience! I don't have a windows machine at hand.

**Comment by raddacle** [comment]
I really appreciate it! I noticed you're also working on 5, thanks for your work.

**Comment by raddacle** [comment]
In the absence of a windows executable. I tried building based on the Readme, however I got an error:

[2019-05-20T06_43_29_238Z-debug.log](https://github.com/kytwb/ferdi/files/3196577/2019-05-20T06_43_29_238Z-debug.log)

**Comment by bittner** [comment]
We should really try to make [all-platform automatic builds](https://github.com/meetfranz/franz/releases/) upon releases. Just like Franz and similar projects. Electron builds for almost every installation technology (snaps, flatpack, etc. excluded I believe).

**Comment by kytwb** [comment]
@bittner Done. 
@FairlyIncognito See https://github.com/kytwb/ferdi/releases/tag/Ferdi-5.2.0-beta.3 for Windows executable.

**Comment by bittner** [comment]
Wow! Very cool! :medal_military:
