### ISSUE TITLE
Stop uploading assets to S3 at every build

### ISSUE THREAD

**Issue by kytwb** [kytwb/ferdi#40]
Right now we're uploading assets at every build, which trigger/exceed my free tier limits on AWS S3. This could be enhanced by not uploading assets to S3 at every build, but rather at strategic ones TBD (releases/tags).

**Comment by kytwb** [comment]
Would also speed up builds that will skip the upload part on Travis a bit.

**Comment by vantezzen** [comment]
Good idea, do you have experience with modifying the travis.yml and appveyor.yml?
Is it possible to skip the upload on normal builds and add a manual trigger that builds and uploads to S3?

**Comment by kytwb** [comment]
No problem for AppVeyor, the artifacts are not uploaded to S3. For Travis, we need to change: https://github.com/kytwb/ferdi/blob/e63a7dcb78e5ec122586038352ece48fc8d149d5/.travis.yml#L36
