### ISSUE TITLE
Add password-protection/lock feature

### ISSUE THREAD

**Issue by justus-saul** [kytwb/ferdi#41]
**User story**
I use Ferdi at home and at work. At each places it is possible that other people are using my computer. I don't want them to be able to look into my communication. -> I want to be able to lock Ferdi and I would like to be able to use different passwords for it at home and at work.

**Feature**
- Option to be asked for a password on Ferdi startup
- Button to lock Ferdi -> need to enter a password to access it again
- When locked notifications and audio are disabled
- Option and password are not synchronized and are only set locally

**Franz**
There was a similar request at Franz, but it seems it didn't get much attention from Dev side: https://github.com/meetfranz/franz/issues/810
I think this would be a really nice improvement.

**Comment by vantezzen** [comment]
Great suggestion, here is my suggestion on how this feature could look like:

![Locking Ferdi is possible via the "Lock Ferdi" option](https://user-images.githubusercontent.com/10333196/65024296-d6fde100-d934-11e9-9ef5-e115e3affab2.png)
![Unlock Ferdi with your password](https://user-images.githubusercontent.com/10333196/65024297-d6fde100-d934-11e9-9671-1f52e71f4e66.png)

I don't think this is feature is too hard to implement, I will have a look.

**Comment by justus-saul** [comment]
Looks great imo! Thanks for having a look into it. :)

**Comment by kytwb** [comment]
LGTM! 💪

**Comment by kytwb** [comment]
Also https://github.com/meetfranz/franz/issues/950 and https://github.com/meetfranz/franz/issues/1430. Included in [v5.3.3-beta.2](https://github.com/kytwb/ferdi/releases/tag/v5.3.3-beta.2)

**Comment by ammarmalhas** [comment]
I just installed and tried version 5.3.3-beta.2 there is a major fault with the epassword scheme! On the locked screen you can select menu Ferdi>Settings which opens the settings page, click "X" and you are in the workspace/services ...etc!
The password should lock everything but the "Quit" command!

**Comment by ammarmalhas** [comment]
May i ask what the relationship is between Franz and Ferdi? they are identical but with different colors, even the account I created in Franz is the same in Ferdi!?

**Comment by ammarmalhas** [comment]
Why is this issue marked "Closed"? Is it? Why am I able to comment here if it is indeed closed?

**Comment by vantezzen** [comment]
> Why is this issue marked "Closed"? Is it? Why am I able to comment here if it is indeed closed?

This issue is closed but not locked. We closed it as the feature requested has been implemented but didn't lock in case there are more comments about this.

**Comment by Blek182** [comment]
![image](https://user-images.githubusercontent.com/44634813/112725081-ee198800-8f48-11eb-94b5-e9b40e1f5803.png)

It's Locked Forever, how to unlock? This is what happen when i click "Enable Password Lock"
![image](https://user-images.githubusercontent.com/44634813/112725115-23be7100-8f49-11eb-88cd-72ae61f01fc4.png)

**Comment by Blek182** [comment]
Yes, it's happen twice.. Error Lock.. After Press Enable Password Lock.. Purple Blank show and i can't do anything. It's Locked Forever lol. I am using Latest Portable Version BTW.
