### ISSUE TITLE
Password lock field gets repopulated with default password

### ISSUE THREAD

**Issue by justus-saul** [kytwb/ferdi#46]
Ferdi version: Ferdi-5.3.3-beta.2
OS: Ubuntu 18.04.3 LTS

After enabling the password lock feature in the settings the password field is prepolulated with the default password "ferdi". When I now want to clean the field to enter my own password, the field gets automatically repopulated with the default password as soon as the last digit in the field is deleted.

**Comment by vantezzen** [comment]
Thank you for your feedback, the issue should be fixed in the next beta build.

Leaving this issue open until next beta build is published to prevent duplicate issues.

**Comment by kytwb** [comment]
Fixed in [v5.3.3](https://github.com/kytwb/ferdi/releases/tag/v5.3.3).
