### ISSUE TITLE
About menu item now in Todos menu?

### ISSUE THREAD

**Issue by bittner** [kytwb/ferdi#47]
**Describe the bug**

As of version 5.3.3, the "About Ferdi" menu item is found in the new Todos menu. Is this normal? This must be a bug, or at least it's veeery uncommon. :roll_eyes: :smile: 

**To Reproduce**
1. Open Ferdi
2. Go to the application menu bar and search for the "About Ferdi" menu item
3. Find the "About Ferdi" menu item in the "Todos" menu
4. There is no "About Ferdi" menu item in neither the "?" menu (natural place) or the "Window" menu (Franz' former choice)

**Expected behavior**

The "About Ferdi" menu item should be located in the "?" menu (or at least at the same location as Franz has it, provided this is hopefully intuitive).

**Screenshots**

![ferdi-menubar-todos](https://user-images.githubusercontent.com/665072/65125907-9070bb00-d9f6-11e9-819c-ed85ecf7afd2.png)

![ferdi-menubar-window](https://user-images.githubusercontent.com/665072/65125913-96ff3280-d9f6-11e9-81dd-d7123d8d95b2.png)

![ferdi-menubar-help](https://user-images.githubusercontent.com/665072/65125929-9e264080-d9f6-11e9-9b2a-1aa2a5a9c762.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu GNU/Linux 18.04.3 LTS Bionic
 - Browser: my favorite is Firefox (probably not relevant, haha) :smirk: :smile: 
 - Version: GNOME 3.28.2

**Smartphone (please complete the following information):**
 - Device: [Librem 5](https://puri.sm/products/librem-5/) - _the phone that respects your privacy_ :lock: :free: :rocket: 
 - OS: PureOS - _aiming for UbuntuTouch (aka UBports) in the long run_ :nerd_face: 
 - Browser: [GNOME stock browser](https://duckduckgo.com/?q=librem+5+browser&t=canonical&atb=v155-1&ia=videos&iax=videos&iai=u9X53UGdvX8) (Epiphany)
 - Version: (not yet announced)

**Additional context**

The phone information is a joke, but I donated 100 US$ for the crowdfunding campaign! They are shipping next week!! :smiley: :champagne:

**Comment by vantezzen** [comment]
Very weird, I can't seem to reproduce this bug.
Using v5.3.3 with Todos enabled, the about menu is still inside the Ferdi menu, not the todo menu.

![About Ferdi in the right menu](https://user-images.githubusercontent.com/10333196/65139048-45fa3900-da0c-11e9-8066-f6103317a44e.png)
![Using v5.3.3](https://user-images.githubusercontent.com/10333196/65139049-45fa3900-da0c-11e9-8073-ad17a7fc77ef.png)

**Comment by justus-saul** [comment]
I am able to reproduce it on Ubuntu 18.04.3 LTS with Ferdi 5.3.3

**Comment by vantezzen** [comment]
Ok, thank you. It looks like Mac uses a different method to build the menu thus the "About Ferdi" option is still in the right place there but not on all other platforms.

It looks like this is the code that is responsible for this: https://github.com/kytwb/ferdi/blob/b2d887bd5f0775bec6708dc10710c1528f6576ad/src/lib/Menu.js#L867
It pushed the option to the 6th submenu, which was previously the last submenu but is now used for the Todo menu. This should mean that Franz has the same issue.

I have now commited fd8220b, which should have fixed this problem. Hope you can test it in the next beta build.

**Comment by kytwb** [comment]
@all-contributors add @bittner for bug

**Comment by kytwb** [comment]
@bittner shipped in [v5.3.4-beta.1](https://github.com/kytwb/ferdi/releases/tag/v5.3.4-beta.1). Can you please test and confirm if the issue is fixed or not on your platform with this version? 🙏

**Comment by deadmeu** [comment]
> @bittner shipped in [v5.3.4-beta.1](https://github.com/kytwb/ferdi/releases/tag/v5.3.4-beta.1). Can you please test and confirm if the issue is fixed or not on your platform with this version? pray

Looks good for me

**Comment by kytwb** [comment]
@deadmeu thanks for the feedback!  
@bittner please let us know if we need to re-open! 🙏

**Comment by bittner** [comment]
The "About Ferdi" is in the right place now (the "?" menu). But the "Todo" menu is empty now, which is a bit ... err ... funny! :smile: 

Specifically, it has a disabled menu item that says "(empty)".

**Comment by vantezzen** [comment]
Oh, the todo menu creation threw an error as it used `window.franz` instead of `window.ferdi`. 28a7345 should have fixed this error now.
