### ISSUE TITLE
Update task menu shortcut icon to the new Ferdi icon

### ISSUE THREAD

**Issue by deadmeu** [kytwb/ferdi#49]
**Describe the solution you'd like**
The new Ferdi icon should replace the existing Franz icon when the app is searched for in the user's task menu.

**Additional context**
Here's the current icon that displays when I search for the Ferdi app in my task menu (XFCE on Arch Linux):
![ferdi franz icon](https://user-images.githubusercontent.com/12111013/65151947-65c04a00-da6a-11e9-9589-a47f9cca88b0.png)

**Comment by vantezzen** [comment]
Hmm, I can't find any remaining Franz icons inside the code. Does anyone know anything more about where this image could come from?

**Comment by AGCaesar** [comment]
I have the icon in /usr/share/icons/Numix-Circle/48/apps/franz.svg
I do not really know how icons works, but that is the place and it is somehow linked to this I guess :)

**Comment by deadmeu** [comment]
> Hmm, I can't find any remaining Franz icons inside the code. Does anyone know anything more about where this image could come from?

On second thoughts, I think this may come from the fact that I'm using the [ferdi-git AUR package](https://aur.archlinux.org/packages/ferdi-git/) to install Ferdi on my machine. Within the PKGBUILD's ferdi.desktop desktop entry, there appears the line: `Icon=franz` which may very well be the reason the Franz icon is appearing.
I'll raise this issue with the AUR package maintainer, and hopefully all the users of that package will have this bug fixed soon.

**Comment by AGCaesar** [comment]
> I'll raise this issue with the AUR package maintainer, and hopefully all the users of that package will have this bug fixed soon.
That will be me... But to be honest I am quite a noob concerning building aur packages. I will change it immediately and lets see what happens :)

**Comment by kytwb** [comment]
@all-contributors please add @AGCaesar for platform

**Comment by AGCaesar** [comment]
@deadmeu did it work? I do not have menu Items as I use rofi so I can not check myself :)

**Comment by AGCaesar** [comment]
I installed a VM with manjaro (because I am lazy) to check it it works and it seems to be fixed. 
But I guess we should wait for feedback from @deadmeu before closing :)

**Comment by deadmeu** [comment]
> I installed a VM with manjaro (because I am lazy) to check it it works and it seems to be fixed.
> But I guess we should wait for feedback from @deadmeu before closing :)

Just upgraded, and it looks good! :smile:
Thank you for your efforts maintaining the package @AGCaesar.
