### ISSUE TITLE
Detach fork from meetfranz/franz

### ISSUE THREAD

**Issue by kytwb** [kytwb/ferdi#57]
As we have hard-forked, I've asked GitHub support to detach `kytwb/ferdi` from `meetfranz/franz`.

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support or GitHub Premium Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

![Screen Shot 2019-09-19 at 4 38 09 PM](https://user-images.githubusercontent.com/412895/65232756-e418fc80-dafb-11e9-933b-d574877be904.png)

Waiting to hear back from GitHub.

**Comment by kytwb** [comment]
![Screen Shot 2019-09-19 at 4 51 07 PM](https://user-images.githubusercontent.com/412895/65233877-c187e300-dafd-11e9-9538-c312efd7bfb8.png)

**Comment by vantezzen** [comment]
Yes, ferdi is not detached!

**Comment by kytwb** [comment]
Should be within the hour! 😉
