### ISSUE TITLE
RocketChat: Make self-hosted generally available

### ISSUE THREAD

**Issue by bittner** [kytwb/ferdi#6]
In Franz only the official RocketChat service can be added. If you self-host it (e.g. as a community chat) you'd have to upgrade to Premium.

Technically, this is a deliberate and arbitrary limitation. It's technically simple to allow any host as a target by using a different URL. Nothing more.

We should make it a free choice to use any URL or host name as an alternative to `<team>.rocket.chat`.

**Comment by bittner** [comment]
Does anyone understand which portions of the code need to be touched to make the necessary changes? I'd be happy to provide the changes in a PR with some support from a helping hand. :grimacing:

**Comment by vantezzen** [comment]
Fixed by #17, should be available in v5.3.0

**Comment by kytwb** [comment]
[Ferdi-5.3.0](https://github.com/kytwb/ferdi/releases/tag/Ferdi-5.3.0) has been released! 🎉

**Comment by bittner** [comment]
You are soooooooooo

```
   ('-.      (`\ .-') /`   ('-.    .-')                _   .-')       ('-.  ,---.,---. 
  ( OO ).-.   `.( OO ),' _(  OO)  ( OO ).             ( '.( OO )_   _(  OO) |   ||   | 
  / . --. /,--./  .--.  (,------.(_)---\_) .-'),-----. ,--.   ,--.)(,------.|   ||   | 
  | \-.  \ |      |  |   |  .---'/    _ | ( OO'  .-.  '|   `.'   |  |  .---'|   ||   | 
.-'-'  |  ||  |   |  |,  |  |    \  :` `. /   |  | |  ||         |  |  |    |   ||   | 
 \| |_.'  ||  |.'.|  |_)(|  '--.  '..`''.)\_) |  |\|  ||  |'.'|  | (|  '--. |  .'|  .' 
  |  .-.  ||         |   |  .--' .-._)   \  \ |  | |  ||  |   |  |  |  .--' `--' `--'  
  |  | |  ||   ,'.   |   |  `---.\       /   `'  '-'  '|  |   |  |  |  `---..--. .--.  
  `--' `--''--'   '--'   `------' `-----'      `-----' `--'   `--'  `------''--' '--'  
```

**Comment by bittner** [comment]
**Fun fact:** If you configure Rocket Chat services in Ferdi they will open just like "normal" in Franz, too.

Haha! :smile: 

Seems like it's really just a simple restriction on the Franz user interface. :+1:
