### ISSUE TITLE
Allow hiding menubar

### ISSUE THREAD

**Issue by bittner** [kytwb/ferdi#7]
It should be possible to hide the menubar. Afterwards, pressing the <kbd>Alt</kbd> key should reveal it (just like Firefox and the RocketChat Electron app).

Franz is silently ignoring this feature request for a long time.

## References

- https://github.com/meetfranz/franz/issues/833 -- _Unable to hide menubar_

**Comment by bittner** [comment]
This seems to be the [code portion](https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/src/main/menus.js#L312-L315) in the Rocket-Chat Electron client that implements the autohiding:
```javascript
mainWindow.setAutoHideMenuBar(!showMenuBar);
mainWindow.setMenuBarVisibility(!!showMenuBar);
```
... with the `mainWindow` being created in [mainWindow/index.js](https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/src/main/mainWindow/index.js).

**Comment by bittner** [comment]
User @khamer mentioned in https://github.com/meetfranz/franz/issues/833#issuecomment-514627530 that the following code works for hiding the menu bar, when run via the Developer Tools:

```javascript
require('electron').remote.getCurrentWindow().setAutoHideMenuBar(true)
```

**Comment by kytwb** [comment]
It's been a bit busy lately, but I'll allocate some time to address some of the open issues over the week-end 🙏

**Comment by vantezzen** [comment]
Hello,
I've just implemented this feature, similar to how RocketChat handles it:
The menubar is shown by default. In the menubar there is a new checkbox, "Auto-hide menu bar". Enabling this will set `remote.getCurrentWindow().setAutoHideMenuBar(true)`, as suggested by you. This setting will persist between restarts as the value is stored in the app settings.

**Comment by kytwb** [comment]
@vantezzen I like the idea of a release candidate (rc) pre-release that includes bug fixes / improvements until next official release version in sync with Franz. WDYT?

**Comment by vantezzen** [comment]
@kytwb Good idea, I would follow the naming scheme of Franz pre-releases (v5.X.X-beta.X). This way the pre-releases should be able to Ferdi's "Include beta versions" feature.

**Comment by kytwb** [comment]
How do we know what the beta version is going to be? patch up? minor up?

**Comment by vantezzen** [comment]
Best is is to patch up, Franz won't minor up too often.

I also think we could release new patch versions of Ferdi without Franz having that version yet (e.g. 5.3.3) if we want to release new features for Ferdi. But I do still think that we should keep minor and major version numbers in sync with Franz.

**Comment by kytwb** [comment]
LGTM! Will go with that 👍

**Comment by kytwb** [comment]
Available in [v5.3.3-beta.1](https://github.com/kytwb/ferdi/releases/tag/v5.3.3-beta.1).

**Comment by bittner** [comment]
> The menubar is shown by default. In the menubar there is a new checkbox, "Auto-hide menu bar".

@vantezzen I can't find this option anywhere in the menu bar. (Note that I'm running Ferdi on Ubuntu Bionic using the GNOME desktop.) Where is this meant to be? Can you maybe post a screenshot here?

It would be weird if this feature were not platform independent. I don't think it has to be.

**Comment by AGCaesar** [comment]
Same here... I can not find the option in the menu bar. Latest build on Arch Linux.

**Comment by bittner** [comment]
Reading commit e9746cbfe61819 I fear the implementation is totally macOS specific. The menu you have added the new menu item to does not exist on other platforms (guessing for Windows and other platforms here).

To make this platform independent I'd suggest to put the new item into the "View" menu. TBO, I don't know if that menu is shown on a Mac; maybe you can check where the "Enter Full Screen" and "Toggle Developer Tools" items are placed, and simply add the new item to that very same menu.

**Comment by vantezzen** [comment]
@bittner Thank you for your help, that was the exact problem. c6356d5 should have fixed the problem, hope you can check if it is fixed in the next beta build.

**Comment by pztrn** [comment]
Hey. Menu item on Windows 10 isn't hiding menu, only when fullscreen (F11).

![изображение](https://user-images.githubusercontent.com/869402/70794930-98a38100-1dc0-11ea-8380-5b6ab9678b71.png)

**Comment by kytwb** [comment]
@pztrn I think this is a regression that has been adressed directly in Electron via https://github.com/electron/electron/pull/21449. The regression should be fixed in the next beta as we updated Electron to include its latest fixes in https://github.com/getferdi/ferdi/commit/06b26716fc90297b4227668c2d6a48e771e02ba7.

**Comment by AlexMuresan** [comment]
Has this been addressed yet? I'm on version 5.5.0 for Ubuntu 18.04 and I can't seem to find this option.

**Comment by bittner** [comment]
Sure, there's the "Auto-hide menu bar" option in the "View" menu, for quite some time. Works on GNU/Linux (Ubuntu Bionic).

**Comment by MadsMighty** [comment]
On Windows the "Auto-hide menu bar" option is not working for me. I can't toggle it with the option under "View" even though the option itself displays properly, and pressing alt does not hide the sidebar. Can someone help with this?

**Comment by GalGreenfield** [comment]
> On Windows the "Auto-hide menu bar" option is not working for me. I can't toggle it with the option under "View" even though the option itself displays properly, and pressing alt does not hide the sidebar. Can someone help with this?

I'm also having this issue. Is there some manual toggle fot it, once it's enabled, maybe? Or some other kind of trigger?

**Comment by ItsANoBrainer** [comment]
Still doesnt work on windows latest version.

**Comment by Disar** [comment]
The "auto-hide" doesn't work on latest but that's likely because for windows the menu is part of the title bar? 
Don't know if that's the case for other OS's. But would explain why auto-hide doesn't work?
Normally the menu would be below it?

**Comment by avielc** [comment]
Yep, still not works, Would really love it to work
