### ISSUE TITLE
Modification to build on Windows

### ISSUE THREAD

**Issue by faaarmer** [kytwb/ferdi#8]
Hi there,
On my machine I couldn't run the `npm run build` command, as gulp would fail with `Task never defined: 'build'`.

In order to fix this, I added the line:
`
gulp.task("build", build);
`

at the end of `gulpfile.babel.js`.

Thanks

**Comment by kytwb** [comment]
Do you want to make a pull request? 😃 Otherwise, I'll cross-check with the original repository first and advise.

**Comment by faaarmer** [comment]
Looks like I have the same issue on the original repo, which makes sense. 
Given there's no other reports of the same issue I can find, it may just be localized to my machine.
I'll just leave it and maybe this issue can help someone if they stumble upon it.

**Comment by kytwb** [comment]
Seems to be working here: https://ci.appveyor.com/project/kytwb/ferdi/builds/25664365
