### ISSUE TITLE
Sustainable process to keep the fork running

### ISSUE THREAD

**Issue by bittner** [kytwb/ferdi#9]
I'm a little bit worried about whether we can keep this fork of Franz actually running. When I look at the GitHub repository today I see:

> This branch is 6 commits ahead, 66 commits behind meetfranz:master.

Does that mean we don't and probably can't pull in updates or enhancements from the Franz code base?

I think it may make sense to identify a sustainable way to keep the fork running, e.g. by maintaining a repository of patches to be applied to Franz to get _unwanted_ feature details out of the code base. (Instead of maintaining the entire code base that then drifts apart hopelessly.) While this definitely requires continuous work keeping the patches working (read: tedious) that shouldn't be too hard, technically.

Can someone explain the current situation and maybe provide some historical details, and the envisioned strategy to go forward?

**Comment by kytwb** [comment]
@bittner I didn't expect this fork to get the attention it's getting to be honest, as I started it for my own need (removing the app delay), but you are right, we should maintain it. I'm happy to add collaborators to the repository! Hola at me 🙌

**Comment by kytwb** [comment]
Sync'd with `upstream/master` for now.

**Comment by kytwb** [comment]
Also, after a quick search: https://github.com/wei/pull

**Comment by kytwb** [comment]
All good; finished to set up Travis (Linux/MacOS) and Appveyor (Windows) for continuous delivery. I have set up https://github.com/wei/pull, looking forward to seeing it in in action next time upstream has updates.

**Comment by kytwb** [comment]
See https://github.com/kytwb/ferdi/pull/10.

**Comment by kytwb** [comment]
Bot forced pushed https://github.com/kytwb/ferdi/pull/10, re-opening and will address when I can aside of work.

**Comment by bittner** [comment]
I'd suggest to retain a set of (scripted) patches to be applied each time a new Franz release pops up.

This could be something like a `sed` command (or something similar from the JavaScript tool chain) for each feature we want to modify. Ideally, each one supported by a test that proves the introduced change is working.

This may be more reliable to apply each time and more obvious to fix (or selectively leave out, in the worst case) if a change fails. What do you think?

**Comment by kytwb** [comment]
@bittner Figured why the bot forced-push despite the merge conflict. It has been fixed in the Pull GitHub app via https://github.com/wei/pull/commit/6c88502ac3a08bac5aa6cf104b58c6fe860a0e6b#commitcomment-34467229. If working as expected (and now it should), I think the Pull app is what we want and would require low-maintenance (fix conflicts if any and merge, otherwise it's automatically merged and kept in sync with the upstream). I can't picture an elegant solution based on patches/sed but I'd be happy to take a look if you come up with anything.

**Comment by kytwb** [comment]
Re-activated Pull.

**Comment by kytwb** [comment]
Merged https://github.com/kytwb/ferdi/pull/14.
